### ISSUE TITLE
Cross validation: Each sample or set left out once?

### ISSUE THREAD

**Issue by corneliusroemer** [gregpoore/tcga_rebuttal#2]
I wasn't quite sure whether I understood this sentence correctly:
> Gradient boosting machines were applied with 10-fold cross-validation such that every sample was left out once.

If I understand it correclty, you split all samples into ten sets, and leave each _set_ out once, not each _sample_. 

The sentence above appears twice, in captions 1F and 2A.

**Comment by gregpoore** [comment]
@corneliusroemer 

Sorry for the confusion. Both are correct, but my wording was not the clearest:
- The cross-validation uses 10 folds, or ten train-test splits (each 90% train, 10% test). 
- A sample is included in only one of the ten 10% test sets, meaning it only has one prediction assigned to it during the 10-fold cross-validation procedure. This is what I meant by each sample was "left out" only once. However, it is not the clearest language, so I've removed that phrase in captions 1F and 2A.

Thanks for question!
