### ISSUE TITLE
Request for Host-Filtered TCGA FASTQ Files for COAD Cancer (German Samples)

### ISSUE THREAD

**Issue by shubavarshini** [gregpoore/tcga_rebuttal#4]
Dear Gregory D Sepich-Poore,

My name is Shuba Alampalli, and I am a Postdoctoral Scientist at Charité – Universitätsmedizin Berlin, where I am studying the tumor-associated microbiome, particularly in young patients diagnosed with colorectal adenocarcinoma (COAD). Currently, I am investigating microbiome composition through metagenome-assembled genomes from German patient samples, and your TCGA cohort offers an invaluable basis for comparison as a control dataset.

I have been following your research, especially the work in Poore et al. in 2020 and 2024. I noted that the host-filtered TCGA FASTQ files from the 2024 paper [PMID: 38396294] are available upon request. I am particularly interested in obtaining the host-filtered TCGA FASTQ files for COAD cancer samples from Germany, as these would be highly relevant to my research objectives. Access to these files would facilitate a robust comparison, enhancing our understanding of the tumor-associated microbiome across different cohorts.

If it is feasible to share this subset, I would be grateful for any guidance on accessing the data or completing any necessary data-use agreements. I have attached a filtered metadata file, procured from your 2024 paper, listing the sample IDs I would like to work with.

Thank you very much for considering my request. I look forward to the possibility of collaborating, and I would be happy to provide any additional information if needed.

Warm regards,
Shuba Alampalli

[TableS14_COAD_Germany_metadata_RS210clean_filtered_abundances.csv](https://github.com/user-attachments/files/17666370/TableS14_COAD_Germany_metadata_RS210clean_filtered_abundances.csv)

**Comment by gregpoore** [comment]
@shubavarshini Thanks for your note. I'm happy to help get the process started, which will involve folks at UC San Diego. Which email can I reach you at, and do you have access to Globus for file sharing?

**Comment by shubavarshini** [comment]
Thank you @gregpoore. I have a Globus account associated to my github. I have never used it before so I might require instructions. I prefer to use my work email: shuba-varshini.alampalli@charite.de . I also wrote an email to Rob Knight, as he's the corresponding author. But I have not heard from him yet.

**Comment by gregpoore** [comment]
@shubavarshini Thanks! I'm working on getting this set up on the backend and will send you an email when ready.
